server:
  port : 8082



#Kafka Topic
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234!Qw5678
    url: jdbc:mysql://localhost:3306/shopdatabase
  kafka:
    # Перечисляем всех наших брокеров
    bootstrap-servers: localhost:9092
    producer:
      # Настраиваем сериализацию сообщений
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
#        spring.json.use.type.headers: false
        spring:
          json:
            value:
              default:
                type: 'ru.bondarev.email.dto.TransactionDTO'
            type:
              mapping: 'ru.bondarev.transactions.dto.TransactionDTO:ru.bondarev.email.dto.TransactionDTO'
            trusted:
              packages: 'ru.bondarev.transactions.dto'
    topic-json:
      name: order_confirmed

